title: EvanalyticsAlex
logo: assets/images/screenshot-2025-02-10-174800.png
description: "Data Portfolio | Business Intelligence | Analytics & Visualization"
show_downloads: true

# GitHub Pages theme
remote_theme: pages-themes/minimal@v0.2.0

# Jekyll Plugins
plugins:
  - jekyll-remote-theme

# Additional Configurations (Optional)
author: "Evan Alex"
github:
  is_project_page: true
