title: EvanalyticsAlex
logo: assets/images/Screenshot_2025-02-10_174800.png
description: "Data Portfolio | Business Intelligence | Analytics & Visualization"
show_downloads: true

# GitHub Pages theme
remote_theme: pages-themes/modernist@v0.2.0

# Jekyll Plugins
plugins:
  - jekyll-remote-theme

# Additional Configurations
author: "Evangelos"
github:
  is_project_page: true

# Social Links
social:
  linkedin: "https://www.linkedin.com/in/evangelosalexandropoulos/"

# Markdown Processor (Enables GitHub Flavored Markdown for tables)
kramdown:
  input: GFM
